### ISSUE TITLE
How do I start this project？

### ISSUE THREAD

**Issue by tengwang1** [shiroyk/Cowork#1]
I have a problem，Mirror db-doc、db-group、db-user  I can't start，The states are unhealthy.

ps：{"t":{"$date":"2023-11-16T15:12:17.094+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}

**Comment by shiroyk** [comment]
latest commit fix the issue with the mongodb version.

**Comment by tengwang1** [comment]
I've pulled the latest code，But the state is still unhealthy
ps：
1、dependency failed to start: container db-group is unhealthy

**Comment by shiroyk** [comment]
try fetch the Image, works for me.
```
docker-compose pull
docker-compose up
```

**Comment by tengwang1** [comment]
When I executed your first command, the following exception occurred

WARNING: Some service image(s) must be built from source by running:
    docker compose build cowork-eureka cowork-auth cowork-config cowork-doc cowork-group cowork-admin cowork-gateway cowork-user cowork-collab
9 errors occurred:
        * Error response from daemon: pull access denied for cowork-doc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-user, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-auth, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-eureka, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-admin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-config, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-gateway, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-group, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
        * Error response from daemon: pull access denied for cowork-collab, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by shiroyk** [comment]
try remove the old and start.
```
docker-compose down
docker-compose up --build
```

**Comment by tengwang1** [comment]
thank you，I have successfully started
but I have a new problem，When two users work together on a document, one user deletes some characters, which does not seem to synchronize to the other user, who only moves the mouse cursor

**Comment by tengwang1** [comment]
It wasn't a steady reoccurrence. Now it seems to be fine again

**Comment by tengwang1** [comment]
May I ask whether this project will carry out conflict calculation at the back end or the front end

**Comment by tengwang1** [comment]
你是中国人吗？

**Comment by shiroyk** [comment]
在前端写的，这个项目是以前的课程作业

**Comment by tengwang1** [comment]
哈哈哈 我还以为你是外国人，那方便留个wx吗，老哥 嘻嘻

**Comment by tengwang1** [comment]
我留个我的联系方式 ：18630095669
